### ISSUE TITLE
Found memory leak

### ISSUE THREAD

**Issue by BenLampson** [luanniao/Blazor.Component.Antd#10]
Slider Found memory leak

**Comment by BenLampson** [comment]
This is a side question.
If you use the server-render.
The service can use more CPU to handle the task list, while you needn't care about the tasks count.
But if you try to use the client-render, the engine is a single thread(in this time) so if you try to use the js invoke with .NET, there has a lot of instances that need the GC to release. 
So we need to decide how many JSInvoke did we need or use another way to handle those operations

**Comment by BenLampson** [comment]
There's another quest is: How can we use the minimum payment to get the BOM event?

**Comment by VCallMeHero** [comment]
Here has some trace info here, maybe we need another plan with client render
![image](https://user-images.githubusercontent.com/64451140/80440356-2f6d7600-893b-11ea-9c2c-1a8f0381b96d.png)
According to such results, client-side rendering is impossible,
In addition, I found that all the same type of component libraries have such problems, but luanniao appeared in the slider, and other components have not found this problem.
But can you consider whether there is a universal solution?

**Comment by BenLampson** [comment]
?

**Comment by BenLampson** [comment]
![image](https://user-images.githubusercontent.com/15414750/80442062-c687fd00-893e-11ea-960a-483a3ba0b68a.png)
Point is windowevent already is struct type, but I don't know why this type is not released or why the are accumulation so many instances like 4760 when we try to use the slider? 
Maybe the Grid has the same problem we not found yet.

**Comment by BenLampson** [comment]
![image](https://user-images.githubusercontent.com/15414750/80442816-5b3f2a80-8940-11ea-88d8-e4934c50a704.png)
It's a big thing in the project.
The cost of using JSINVOKE is much larger than expected, which may change our implementation strategy. At least in some problems that require immediate monitoring, this is a big problem.
Suspend the development of all components that will have "instant" subscriptions, and handle the issue of the whole group.
Microsoft's own Event also has problems. According to the situation in the actual project, the use of tasks and frequent listening are inevitable. For example, the user performs additional operations while acquiring data, then this problem will be the success or failure of the project. Key points.

**Comment by BenLampson** [comment]
I think we first need to evaluate and enumerate how many cases in the actual project need to "track events closely"?
First of all, what can be determined is: drag and drop (it must also be relative to the entire page, such as the slider that has problems)
Global broadcast event: for example, windowresize, it will be listened by many instances. This is a broadcast. If the event is broadcast, there will be a problem with the broadcast chain, and there will also be a problem with the chain break.
Here you can consider changing the resize event to internal to ensure the stability of the library within the component.

Relying on this, does Canvas also have this problem? And Canvas needs to "listen anytime and anywhere", which may cause us to prefer the JS to implementation, not .NET.
In addition, the approach of Mono's UNO project is also worth reference, but it has basic optimizations in the underlying multi-threading, which is an embarrassing problem.
At present, everyone's implementation is JSInvoke.However, from the perspective of landing, it is impossible to do so.Is it possible to consider designing from Blazor's mechanism?

**Comment by BenLampson** [comment]
[Json Question?]( https://github.com/dotnet/aspnetcore/issues/16210)

**Comment by BenLampson** [comment]
fixed
