### ISSUE TITLE
WebAssembly can not auto update

### ISSUE THREAD

**Issue by VCallMeHero** [luanniao/Blazor.Component.Antd#12]
WebAssembly can not auto update.
23:00 PM is publish point, but I cann't get the new version.

**Comment by BenLampson** [comment]
CDN Needs time to refresh.

**Comment by VCallMeHero** [comment]
:eyes::eyes::eyes::eyes::eyes::eyes:
2020-04-28 23:35:28

**Comment by BenLampson** [comment]
...

**Comment by BenLampson** [comment]
fixed
