### ISSUE TITLE
Legal issues

### ISSUE THREAD

**Issue by VCallMeHero** [luanniao/Blazor.Component.Antd#19]
![image](https://user-images.githubusercontent.com/64451140/80617404-a22e3c80-8a74-11ea-85c5-0ab3995a48f3.png)
Is this is a overwatch loading page???
Is this legal?

**Comment by BenLampson** [comment]
emmmmmmmmmmmmmmmmmmmmmmmmmmmmmm....

**Comment by BenLampson** [comment]
I called Winston, and he said that he doesn't care about this.
![image](https://user-images.githubusercontent.com/15414750/80790859-8df85580-8bc2-11ea-8fed-71d41a65103e.png)
