### ISSUE TITLE
Console has error info

### ISSUE THREAD

**Issue by VCallMeHero** [luanniao/Blazor.Component.Antd#24]
![image](https://user-images.githubusercontent.com/64451140/81131784-e17df100-8f7e-11ea-9454-80ac9ae75236.png)

What happened here?
The page is completely normal, but where do these exceptions come from?
The library must be haven't unhandled exception!

**Comment by BenLampson** [comment]
2020-05-07

**Comment by BenLampson** [comment]
There's three days ago...
