### ISSUE TITLE
Add window scroll and dom sroll event listener

### ISSUE THREAD

**Issue by diwu0510** [luanniao/Blazor.Component.Antd#40]
BackTop组件需要监听window和指定组件的scroll事件，以触发按钮的显示和隐藏

Backup相关js如下：
`
BindBackTop: function (domId, visibilityHeight, targetId) {
        var dom = document.getElementById(domId);
        var container = (!targetId || targetId.toLocaleLowerCase() === "window") ? window : document.getElementById(targetId);
        if (!container || !dom) return;

        dom.style.visibility = "hidden";

        if (container["BackTops"] == undefined || container["BackTops"] == null) {
            container["BackTops"] = [];
            container.addEventListener("scroll", function (e) {
                var top = getScroll(e.target, true);
                for (var i = 0; i < container["BackTops"].length; i++) {
                    var temp = i;
                    var backTop = container["BackTops"][temp];

                    if (top > backTop.height) {
                        backTop.dom.style.visibility = "visible";
                    } else {
                        backTop.dom.style.visibility = "hidden";
                    }
                }
            });
        }

        container["BackTops"].push({ id: domId, dom: dom, height: visibilityHeight, state: 0 });

        dom.onclick = function () {
            //ScrollTop(0, 200)
            if (isWindow(container)) {
                container.scrollTo(window.pageXOffset, 0);
            } else if (container instanceof Document) {
                container.documentElement.scrollTop = 0;
            } else {
                container.scrollTop = 0;
            }
        };

        function getScroll(target, top) {
            if (typeof window === 'undefined') {
                return 0;
            }

            var method = top ? 'scrollTop' : 'scrollLeft';
            var result = 0;

            if (isWindow(target)) {
                result = target[top ? 'pageYOffset' : 'pageXOffset'];
            } else if (target instanceof Document) {
                result = target.documentElement[method];
            } else if (target) {
                result = target[method];
            }

            if (target && !isWindow(target) && typeof result !== 'number') {
                result = (target.ownerDocument || target).documentElement[method];
            }

            return result;
        }

        function isWindow(obj) {
            return obj !== null && obj !== undefined && obj === obj.window;
        }
    }
//////////
RemoveBackTop: function (domId, targetId) {
        console.log("执行了")
        var container = (!targetId || targetId.toLocaleLowerCase() === "window") ? window : document.getElementById(targetId);
        if (!container) return;
        if (!container["BackTops"]) return;
        if (container["BackTops"].length === 0) return;

        for (var i = 0; i < container["BackTops"].length; i++) {
            var temp = i;
            var bt = container["BackTops"][temp];
            if (bt.id === domId) {
                container["BackTops"].splice(temp, 1);
                return;
            }
        }
    }
`

**Comment by BenLampson** [comment]
目前已经增加window级别scroll消息分发
element需要重新构建结构,

**Comment by BenLampson** [comment]
fixed
